### ISSUE TITLE
Issue-fixes #6

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/blockchain-tutorial#27]
Automated Review Comments
Issues in networking/README.md:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
Issues in networking/main.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
