### ISSUE TITLE
Issue-Create README.md

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/blockchain-tutorial#50]
Automated Review Comments
Issues in proof-work/README.md:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')

**Comment by scdnj** [comment]
I got it.
