### ISSUE TITLE
Issue-add proof of stake tutorial

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/blockchain-tutorial#56]
Automated Review Comments
Issues in proof-stake/README.md:
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in proof-stake/main.go:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')

**Comment by scdnj** [comment]
I got it.
