### ISSUE TITLE
Issue-Rename ADDR evnrironment variable to PORT (semantics :))

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/blockchain-tutorial#66]
Automated Review Comments
Issues in main.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in networking/main.go:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in proof-stake/main.go:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in proof-work/main.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
