### ISSUE TITLE
Issue-put CI back

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/blockchain-tutorial#78]
Automated Review Comments
Issues in README.md:
  - (2, 'Line exceeds 80 characters')
Issues in p2p/main.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
